version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  prepare:
    executor: node/default
    steps: 
      - node/install:
          parameters:
            node-version: 12.4.0
      - run: node -v

workflows:
  build:
    jobs:
      - prepare
