version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  prepare:
    executor: node/default
    steps: 
      - node/install:
          node-version: 12.4.0

  install:
    working_directory: ~/pegasus
    executor: node/default
    steps:
        - checkout

workflows:
  build:
    jobs:
      - prepare
      - install:
          requires: 
            - prepare
