version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.4.0
    working_directory: ~/pegasus

jobs:
  build:
    executor: node12
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  release:
    executor: node12
    steps:
      - checkout
      - run: git tag v$(node -pe "require('./package.json').version")
      - run: git push origin v$(node -pe "require('./package.json').version")
      - run: npm install
      - run: npm run release

workflows:
  build:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: /^release.*/